version: '3.9'

services:
  mongodb:
    container_name: sg-public-transport-dashboard
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
